const {useState}=React;
window.CursosSection=function CursosSection({courses=[],onAddCourse,onUpdateCourse,onDeleteCourse,onUploadMaterial,onDeleteMaterial}){
 const palette=['#8b5cf6','#3b82f6','#06b6d4','#10b981','#eab308','#f97316','#ef4444','#ec4899'];
 const empty={name:'',teacher:'',room:'',color:'#8b5cf6',notes:''};
 const [open,setOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(empty),[expanded,setExpanded]=useState(null),[busy,setBusy]=useState(false);
 const start=c=>{setEditing(c);setForm(c?{...c}:empty);setOpen(true)};
 const save=()=>{if(!form.name.trim())return alert('Escribe el nombre del curso.');editing?onUpdateCourse(editing.id,form):onAddCourse({...form,color:form.color||palette[courses.length%palette.length]});setOpen(false)};
 const upload=async(e,c)=>{const f=e.target.files?.[0];if(!f)return;if(f.type!=='application/pdf')return alert('Selecciona un PDF.');if(f.size>45*1024*1024)return alert('El PDF supera 45 MB.');setBusy(true);try{const b=await new Promise((ok,bad)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=bad;r.readAsDataURL(f)});await onUploadMaterial(c.id,f,b)}catch(err){alert(err.message)}finally{setBusy(false);e.target.value=''}};
 return <div className="space-y-5"><div className="card-nox p-4 sm:p-6 rounded-3xl flex flex-col sm:flex-row justify-between gap-4"><div><h2 className="text-xl sm:text-2xl font-bold">Cursos y Materiales</h2><p className="text-xs text-zinc-500">Cada curso tiene color, información y materiales propios.</p></div><button className="nox-primary" onClick={()=>start(null)}>+ Añadir curso</button></div>
 <div className="grid grid-cols-1 md:grid-cols-2 gap-4">{courses.map(c=><div key={c.id} className="card-nox rounded-3xl overflow-hidden" style={{borderTop:`4px solid ${c.color}`}}><div className="p-5"><div className="flex justify-between gap-3"><div><h3 className="font-black text-lg">{c.name}</h3><p className="text-xs text-zinc-500">{c.teacher||'Sin docente'}{c.room?` · ${c.room}`:''}</p></div><div className="w-8 h-8 rounded-full" style={{background:c.color}}/></div><div className="flex gap-2 mt-4"><button className="nox-btn" onClick={()=>start(c)}>Editar</button><button className="nox-btn danger" onClick={()=>onDeleteCourse(c.id)}>Eliminar</button><button className="nox-btn" onClick={()=>setExpanded(expanded===c.id?null:c.id)}>{expanded===c.id?'Ocultar':'Materiales'}</button></div></div>
 {expanded===c.id&&<div className="border-t border-zinc-800 p-4 bg-zinc-950/50"><div className="flex justify-between items-center mb-3"><b className="text-sm">Materiales</b><label className="nox-primary cursor-pointer text-xs px-3 py-2">{busy?'Subiendo...':'+ PDF'}<input type="file" accept=".pdf,application/pdf" hidden disabled={busy} onChange={e=>upload(e,c)}/></label></div>{(c.materials||[]).map((m,i)=><div key={m.id||i} className="flex items-center justify-between gap-2 p-3 rounded-xl bg-zinc-900 mb-2"><div className="text-sm truncate">📄 {m.name||`PDF ${i+1}`}</div><div className="flex gap-2 shrink-0">{m.webViewLink&&<a className="nox-btn text-xs" href={m.webViewLink} target="_blank" rel="noreferrer">Abrir</a>}<button className="nox-btn danger text-xs" onClick={()=>onDeleteMaterial(c.id,m.id)}>Eliminar</button></div></div>)}{!(c.materials||[]).length&&<p className="text-xs text-zinc-600">Sube PDF 1, PDF 2, PDF 3…</p>}</div>}</div>)}</div>
 {!courses.length&&<div className="card-nox p-10 rounded-3xl text-center text-zinc-500">Crea tu primer curso para vincular clases, exámenes, parciales y entregables.</div>}
 {open&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><div className="modal-card"><div className="flex justify-between mb-5"><h3 className="text-xl font-black">{editing?'Editar curso':'Crear curso'}</h3><button className="nox-icon" onClick={()=>setOpen(false)}>×</button></div><div className="space-y-3"><label className="field-label">Nombre<input className="nox-input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ingeniería de Software"/></label><div className="grid grid-cols-2 gap-3"><label className="field-label">Docente<input className="nox-input" value={form.teacher||''} onChange={e=>setForm({...form,teacher:e.target.value})}/></label><label className="field-label">Aula<input className="nox-input" value={form.room||''} onChange={e=>setForm({...form,room:e.target.value})}/></label></div><label className="field-label">Color<div className="flex flex-wrap gap-2 mt-1">{palette.map(p=><button type="button" key={p} onClick={()=>setForm({...form,color:p})} className={`w-9 h-9 rounded-full border-2 ${form.color===p?'border-white':'border-transparent'}`} style={{background:p}}/>)}</div></label><label className="field-label">Notas<textarea className="nox-input" value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="w-full nox-primary" onClick={save}>{editing?'Guardar cambios':'Crear curso'}</button></div></div></div>}
 </div>;
};
