const {useState}=React;
window.EntregablesSection=function EntregablesSection({items=[],courses=[],onAddItem,onUpdateItem,onDeleteItem}){
 const [year,setYear]=useState(new Date().getFullYear()),[month,setMonth]=useState(new Date().getMonth()),[open,setOpen]=useState(false),[editing,setEditing]=useState(null);
 const [form,setForm]=useState({title:'',date:'',time:'23:59',courseId:'',notes:''});
 const name=new Date(year,month).toLocaleString('es-ES',{month:'long'}),data=items.filter(i=>i.type==='entregable'&&new Date(i.date).getFullYear()===year&&new Date(i.date).getMonth()===month);
 const move=d=>{let m=month+d,y=year;if(m>11){m=0;y++}if(m<0){m=11;y--}setMonth(m);setYear(y)};
 const start=x=>{setEditing(x);setForm(x?{...x}:{title:'',date:new Date(year,month,20).toISOString().slice(0,10),time:'23:59',courseId:'',notes:''});setOpen(true)};
 const save=()=>{if(!form.title.trim()||!form.date)return alert('Completa el trabajo y la fecha.');const c=courses.find(x=>x.id===form.courseId),item={...form,type:'entregable',courseName:c?.name||'',color:c?.color||'#eab308',status:editing?.status||'pendiente'};editing?onUpdateItem(editing.id,item):onAddItem(item);setOpen(false)};
 return <div className="space-y-6"><div className="card-nox p-4 sm:p-6 rounded-3xl flex flex-col sm:flex-row justify-between gap-4"><div><h2 className="text-xl sm:text-2xl font-bold capitalize">Entregables · {name} {year}</h2><p className="text-xs text-zinc-500">Trabajos pendientes y fechas límite.</p></div><div className="flex gap-2"><button className="nox-btn" onClick={()=>move(-1)}>←</button><button className="nox-btn" onClick={()=>move(1)}>→</button><button className="nox-primary" onClick={()=>start()}>+ Nuevo trabajo</button></div></div>
 <div className="space-y-3">{data.map(x=><div key={x.id} className="card-nox p-4 rounded-2xl flex justify-between gap-3"><div><div className="text-yellow-400 text-xs font-bold">Entrega: {x.date} · {x.time}</div><b>{x.title}</b><p className="text-xs text-zinc-500">{x.courseName||'Sin curso'}{x.notes?` · ${x.notes}`:''}</p></div><div className="flex gap-2"><button className="nox-btn" onClick={()=>start(x)}>Editar</button><button className="nox-btn danger" onClick={()=>onDeleteItem(x.id)}>Eliminar</button></div></div>)}{!data.length&&<div className="card-nox p-8 rounded-3xl text-center text-zinc-500">No hay entregables este mes.</div>}</div>
 {open&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><div className="modal-card"><div className="flex justify-between mb-5"><h3 className="text-xl font-black">{editing?'Editar entregable':'Nuevo entregable'}</h3><button className="nox-icon" onClick={()=>setOpen(false)}>×</button></div><div className="space-y-3"><label className="field-label">Curso<select className="nox-input" value={form.courseId} onChange={e=>setForm({...form,courseId:e.target.value})}><option value="">Sin curso</option>{courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field-label">Título<input className="nox-input" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><div className="grid grid-cols-2 gap-3"><label className="field-label">Fecha límite<input type="date" className="nox-input" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label className="field-label">Hora límite<input type="time" className="nox-input" value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/></label></div><label className="field-label">Notas<textarea className="nox-input" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="w-full nox-primary" onClick={save}>{editing?'Guardar cambios':'Crear entregable'}</button></div></div></div>}
 </div>;
};
